### ISSUE TITLE
Stream speeding up

### ISSUE THREAD

**Issue by angelkawaiix** [amazeedaizee/CustomStreamMaker#4]
It's incredibly hard to tell if IM just doing something wrong, but whenever I try playing the stream on the Needy Streamer Overload game, it rushes through the stream and ends it almost immediately, not letting text fully play through or animations fully play. I'd love to use your stream maker because i much prefer it to the one in game since it feels more natural to the game itself, but i simply cant get it to play at a normal speed.

**Comment by amazeedaizee** [comment]
Hello, sorry that the program or mod isn't working correctly! The stream ending immediately can happen if for some reason there isn't a valid .json file that represents a saved stream in the custom stream loader folder. The custom stream loader mod should be in its own separate folder (named "CustomStreamLoader") in the BepInEx plugins folder with the mod dll and a valid .json file; this is so that the program can also detect if this mod is installed to load saved streams directly from the program.

-----

In the case that you verified that all of the above is working properly, can you tell me:
- What version of the custom stream maker you're using?
- What version of the custom stream loader you're using?
- What version of the game you're using?
- What version of BepInEx you're using?
- What operating system you're using, and what version?

**Comment by angelkawaiix** [comment]
Oh my god I'd like to highly apologize for bugging you! Realized I was just using it totally wrong. The issue was I didn't have stream comments between each animation/the ending, causing it to rush through instead of pausing between each action. Thank you so much for taking time out of your day to try and help!
